# SPDX-FileCopyrightText: 2024 Frans van Dorsselaer
#
# SPDX-License-Identifier: GPL-3.0-only

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions: {}

jobs:
  REUSE:
    uses: dorssel/workflows/.github/workflows/REUSE.yml@055b817a1d43824fe92c35961ccc450a0072fd44
    permissions:
      contents: read
      pull-requests: write

  MegaLinterNET:
    uses: dorssel/workflows/.github/workflows/mega-linter-dotnet.yml@055b817a1d43824fe92c35961ccc450a0072fd44
    permissions:
      contents: read
      pull-requests: write
